#!/bin/bash

TARGET=schemafw

wi_xsli=$( which xsl-import )
if [ -n wi_xsli ]; then
    cd web_includes
    xsl-import -s sfw_debug.xsl > sfw_compiled.xsl
    cd ..
else
    echo
    echo "Install xsl-import to compile the stylesheets into a single stylesheet."
    echo "cd /usr/local/lib"
    echo "sudo git clone https://www.github.com/cjungmann/xsl-import"
    echo "cd /usr/local/bin"
    echo "sudo cp -s /usr/local/lib/xsl-import/xsl-import ."
    echo
fi

wi_uglify=$( which uglifyjs )
if [ -n wi_uglify ]; then
    scripts=(
        sfw_*.js
        classes.js
        dpicker.js
        Events.js
        Dialog.js
        Moveable.js
        XML.js)

    cd web_includes
    # Skip --compress because it discards lambda functions among other necessities.
    uglifyjs ${scripts[@]} --verbose --mangle --output sfw.min.js
    uglifyjs XML.js --mangle --output XML.min.js
    cd ..
else
    echo
    echo "Install uglify-js to minify the javascript library."
    echo "sudo apt-get install uglify-js"
    echo
fi

install -D --mode=644 web_includes/* -t /usr/local/lib/${TARGET}/web_includes/
install --mode=644    default.xsl    /usr/local/lib/${TARGET}/

./install-info

