#!/bin/bash

testroutine_first=ssys_schemafw_version
testroutine_backup=ssys_get_procedure_params

function updatedbs
{
    db_query="SELECT ROUTINE_SCHEMA FROM ROUTINES WHERE ROUTINE_NAME='$1'"
    dbs=$(mysql information_schema -NB -e "${db_query}")
    dbcount=$( echo "${dbs}" | wc -w )

    if [ $dbcount -eq 0  ] ; then
        if [ $1 == $testroutine_backup ] ; then
            echo No SchemaFW databases found: done.
        else
            echo "No databases, checking for procedure ${testroutine_backup}."
            updatedbs ${testroutine_backup}
        fi
    else
        echo About to update databases "${dbs}"

        read -rsp $"Press space to continue..." -n1 key
        if [ "$key" = '' ] ; then
            while read -r dbname; do
                echo
                echo
                echo "Updating ${dbname}"
                mysql -Bf -D ${dbname} < sys_procs.sql
            done <<< "${dbs}"
        fi
    fi
}


updatedbs ${testroutine_first}

